- name: Add metrics-server Helm repository
  kubernetes.core.helm_repository:
    name: metrics-server
    repo_url: https://kubernetes-sigs.github.io/metrics-server/

- name: Update Helm repositories
  kubernetes.core.helm_repository:
    name: metrics-server
    repo_url: https://kubernetes-sigs.github.io/metrics-server/
    state: present
    force_update: yes

- name: Install metrics-server using Helm
  kubernetes.core.helm:
    name: metrics-server
    chart_ref: metrics-server/metrics-server
    release_namespace: kube-system
    create_namespace: false
    state: present
    values: {}