- name: "[control-plane/worker]: Ensure net.ipv4.ip_forward is set to 1"
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: "[control-plane/worker]: Update apt package index"
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: "[control-plane/worker]: Update YUM package index"
  ansible.builtin.yum:
    update_cache: yes
  when: ansible_os_family.lower() == 'redhat' and ansible_distribution_major_version >= '9' 

- name: "[control-plane/worker]: Ensure required packages are installed"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - bash-completion
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: "[control-plane/worker]: Ensure required packages are installed on RedHat"
  ansible.builtin.yum:
    name:
      - yum-utils
      - ca-certificates
      - curl
      - gnupg2
      - bash-completion
    state: present
  when: ansible_os_family.lower() == 'redhat' and ansible_distribution_major_version >= '9' 

# - name: Ensure zsh is installed
#   ansible.builtin.package:
#     name: zsh
#     state: present

# - name: Change default shell to zsh for the current user
#   ansible.builtin.shell: chsh -s /bin/zsh {{ ansible_user }}

# - name: Install Oh My Zsh
#   ansible.builtin.git:
#     repo: https://github.com/ohmyzsh/ohmyzsh.git
#     dest: /home/{{ ansible_user }}/.oh-my-zsh
#     version: master
#   become: yes
#   become_user: "{{ ansible_user }}"

# - name: Copy the default .zshrc provided by Oh My Zsh
#   ansible.builtin.copy:
#     src: /home/{{ ansible_user }}/.oh-my-zsh/templates/zshrc.zsh-template
#     dest: /home/{{ ansible_user }}/.zshrc
#     remote_src: yes
#   become: yes
#   become_user: "{{ ansible_user }}"
- block:
  - name: "[control-plane/worker]: Add Kubernetes GPG key"
    rpm_key:
      state: present
      key: https://packages.cloud.google.com/yum/doc/yum-key.gpg

  - name: "[control-plane/worker]: Add Kubernetes repository"
    ansible.builtin.yum_repository:
      name: kubernetes
      description: Kubernetes
      baseurl: "https://pkgs.k8s.io/core:/stable:/{{ kub_package_version }}/rpm/"
      gpgcheck: 1
      repo_gpgcheck: 1
      gpgkey: "https://pkgs.k8s.io/core:/stable:/{{ kub_package_version }}/rpm/repodata/repomd.xml.key"
      enabled: yes

  - name: "[control-plane/worker]: Update YUM package index after adding Kubernetes repository"
    ansible.builtin.yum:
      update_cache: yes

  - name: "[control-plane/worker]: Install Kubernetes tools (kubelet, kubeadm, kubectl)"
    ansible.builtin.yum:
      name:
        - kubelet
        - kubeadm
        - kubectl
        - python3-dnf-plugin-versionlock
      state: present

  - name: "[control-plane/worker]: Hold Kubernetes tools (kubelet, kubeadm, kubectl)"
    ansible.builtin.command: yum versionlock add kubelet kubeadm kubectl

  - name: "[control-plane/worker]: Create systemd configuration for Kubelet"
    template:
      src: kubelet-systemd.service.j2
      dest: /usr/lib/systemd/system/kubelet.service
      mode: '0644'
  
  - name: "[control-plane/worker]: Reload systemd daemon"
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: "[control-plane/worker]: Enable and start kubelet service"
    ansible.builtin.systemd:
      name: kubelet
      enabled: yes
      state: started

  - name: "[control-plane/worker]: Add Docker repository"
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo

  - name: "[control-plane/worker]: Update YUM package index after adding Docker repository"
    ansible.builtin.yum:
      update_cache: yes

  - name: "[control-plane/worker]: Install containerd"
    ansible.builtin.yum:
      name: containerd
      state: present

  when: ansible_os_family.lower() == 'redhat' and ansible_distribution_major_version >= '9' 

- block:
  - name: "[control-plane/worker]: Download Kubernetes package signing key"
    get_url:
      url: "https://pkgs.k8s.io/core:/stable:/{{ kub_package_version }}/deb/Release.key"
      dest: /tmp/kubernetes-release.key
      mode: '0644'

  - name: "[control-plane/worker]: Create directory for keyring if it doesn't exist"
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: "[control-plane/worker]: Convert the signing key to GPG keyring format"
    command: >
      gpg --dearmor
      --output /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      /tmp/kubernetes-release.key
    args:
      creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: "[control-plane/worker]: Remove the downloaded raw key file"
    file:
      path: /tmp/kubernetes-release.key
      state: absent

  - name: "[control-plane/worker]: Add Kubernetes APT source"
    ansible.builtin.lineinfile:
      path: /etc/apt/sources.list.d/kubernetes.list
      line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kub_package_version }}/deb/ /"
      create: yes

  - name: "[control-plane/worker]: Update apt package index after adding Kubernetes repository"
    ansible.builtin.apt:
      update_cache: yes

  - name: "[control-plane/worker]: Install Kubernetes tools (kubelet, kubeadm, kubectl)"
    ansible.builtin.apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: present

  - name: "[control-plane/worker]: Hold Kubernetes tools (kubelet, kubeadm, kubectl)"
    ansible.builtin.command: apt-mark hold kubelet kubeadm kubectl

  - name: "[control-plane/worker]: Create systemd configuration for Kubelet"
    template:
      src: kubelet-systemd.service.j2
      dest: /usr/lib/systemd/system/kubelet.service
      mode: '0644'
  
  - name: "[control-plane/worker]: Reload systemd daemon"
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: "[control-plane/worker]: Enable and start kubelet service"
    ansible.builtin.systemd:
      name: kubelet
      enabled: yes
      state: started

  - name: "[control-plane/worker]: Install containerd"
    ansible.builtin.apt:
      name: containerd
      state: present

  when: ansible_distribution == 'Ubuntu'

# - name: Configure containerd
#   ansible.builtin.command: containerd config default > /etc/containerd/config.toml
#   args:
#     creates: /etc/containerd/config.toml
- name: "[control-plane/worker]: Create /etc/containerd directory if it does not exist"
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: "[control-plane/worker]: Configure containerd with systemd cgroup driver"
  ansible.builtin.template:
    src: containerd-config-v2.toml.j2
    dest: /etc/containerd/config.toml
    mode: '0644'

- name: "[control-plane/worker]: Restart containerd"
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: "[control-plane/worker]: Generate systemd containerd.service from template"
  ansible.builtin.template:
    src: containerd-systemd.service.j2
    dest: /usr/lib/systemd/system/containerd.service
    mode: '0644'

- name: "[control-plane/worker]: Reload systemd daemon"
  ansible.builtin.systemd:
    daemon_reload: yes

- name: "[control-plane/worker]: Enable and start containerd service"
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: started

- name: "[control-plane/worker]: Create kubeadm-config.yaml"
  copy:
    content: |
      kind: ClusterConfiguration
      apiVersion: kubeadm.k8s.io/v1beta4
      kubernetesVersion: {{kub_version}}
      ---
      kind: KubeletConfiguration
      apiVersion: kubelet.config.k8s.io/v1beta1
      cgroupDriver: systemd
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: '0644'

- set_fact:
    ips: "{{ hosts | map(attribute='ip')| list}}"

- set_fact:
    host_line: "{{ k8s_controlplane_endpoint_ip }} {{ k8s_controlplane_endpoint_hostname }}"
  when: k8s_controlplane_endpoint_ip not in ips

- set_fact:
    host_line: "{{ k8s_controlplane_endpoint_ip }} {{ hosts | selectattr('ip', 'equalto', k8s_controlplane_endpoint_ip) | map(attribute='shortname') | first }} {{ hosts | selectattr('ip', 'equalto', k8s_controlplane_endpoint_ip) | map(attribute='fqdn') | first }}  {{ k8s_controlplane_endpoint_hostname }}"
  when: k8s_controlplane_endpoint_ip in ips

- name: "[control-plane/worker]: Ensure entry for k8s_controlplane_endpoint_hostname exists in /etc/hosts"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{k8s_controlplane_endpoint_ip}}'
    line: "{{ host_line }}"
    state: present

- name: "[control-plane/worker]: Ensure entry for k8s_controlplane_endpoint_hostname exists in /etc/hosts"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{item.ip}}'   
    state: present
    line: "{{ item.ip }} {{item.fqdn}}"
    # line: "{{ item.ip }} {{item.shortname}} {{item.fqdn}}"
  with_items: "{{ hosts }}"
  when: item.ip != k8s_controlplane_endpoint_ip

# - name: Allow all traffic from private network
#   ansible.builtin.firewalld:
#     source: "{{ private_network }}"
#     zone: public
#     permanent: yes
#     state: enabled

# - name: Reload firewalld
#   ansible.builtin.systemd:
#     name: firewalld
#     state: restarted

- block:
  - name: "[control-plane/worker]: Create /run/systemd/resolve directory if it does not exist"
    file:
      path: /run/systemd/resolve
      state: directory
      mode: '0755'

  - name: "[control-plane/worker]: Link /etc/resolv.conf to /run/systemd/resolve/resolv.conf"
    ansible.builtin.file:
      src: /etc/resolv.conf
      dest: /run/systemd/resolve/resolv.conf
      state: link

  - name: "[control-plane/worker]: Restart kubelet service"
    ansible.builtin.systemd:
      name: kubelet
      state: restarted

  when: ansible_os_family.lower() == 'redhat'