---
- name: Install HAProxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Enable and start HAProxy service
  ansible.builtin.systemd:
    name: haproxy
    enabled: yes
    state: started

- name: Configure HAProxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Enable and start HAProxy service
  ansible.builtin.systemd:
    name: haproxy
    enabled: yes
    state: restarted

